[project]
name = "ioe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sabin Shrestha", email = "sabin.shrestha.er@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "langchain-ollama>=1.1.0",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
    "ruff>=0.16.3",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
ioe = "ioe.main:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
