"""Write the evaluation suite out as a readable table.

    uv run python notes/list_tests.py

Produces notes/defense/test-cases.md. Reads src/ioe/eval.py directly and runs no model,
so it is instant and cannot disagree with the suite it documents -- which is the point.
A test list transcribed by hand is wrong the first time a case is added.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from ioe import eval as suite

OUT = Path(__file__).resolve().parents[1] / "notes" / "defense" / "test-cases.md"

# One line on what each group is protecting, so the table is readable without the source.
# Defined as constants rather than inline, because implicit string concatenation inside a
# collection literal is the one place it reads as a missing comma.
_FEES = (
    "Every fee question must reach the worked totals -- and the entrance examination fee "
    "and the application form fee, which are different money, must not."
)
_RESULTS = (
    "The published pass list, answered by exact lookup rather than by retrieval. A form "
    'number that is not on the list must still reach the lookup: "not found" is the '
    "correct answer, and inventing a candidate is the failure."
)
_DOCS = "Ordinary expository questions, answered from the thirteen indexed notices."
_LANGUAGE = (
    "A question written in Devanagari, or one asking for another language, must still "
    "reach the documents and still be answered in English."
)
_SCOPE = (
    "What the notices do not cover. `declined` is the app refusing without a model call; "
    "`uncovered` is retrieval finding nothing, which still gets a real answer."
)
_CUTOFFS = (
    "Published closing ranks. A rank the student states about themselves must not be "
    "looked up as a person -- that would print a stranger's name and district beside real "
    "admission figures."
)
_CHANCES = (
    "The 2083 allocation and the four years of published cut-offs answer different "
    "questions and must stay in their own lanes. Only a question about the priority form "
    "reaches the allocation."
)
_SEATS = "Published admission targets per campus and programme."

GROUPS = {
    "fees": ("Fees", _FEES),
    "results": ("Results", _RESULTS),
    "docs": ("Retrieval", _DOCS),
    "language": ("Language", _LANGUAGE),
    "scope": ("Scope", _SCOPE),
    "cutoffs": ("Cut-offs", _CUTOFFS),
    "chances": ("Chances", _CHANCES),
    "seats": ("Seats", _SEATS),
}

# What each evidence name means, in a phrase.
MEANS = {
    "documents": "retrieved passages",
    "lookup": "exact pass-list record",
    "fees": "worked fee totals",
    "seats": "published seat table",
    "priority": "priority-order rules",
    "chances": "2083 allocation, simulated",
    "cutoffs": "published closing ranks",
    "notices": "live notice listings",
    "dates": "BS/AD conversions",
    "uncovered": "no source matched",
    "declined": "refused, no model call",
}


def names(items: set[str]) -> str:
    return ", ".join(f"`{name}`" for name in sorted(items)) if items else "—"


def main() -> None:
    out: list[str] = []
    cases = suite.CASES
    conv_turns = sum(len(turns) for _, turns in suite.CONVERSATIONS)
    figures = sum(len(turns) for _, turns in suite.FIGURES)
    total = len(cases) + conv_turns + figures

    out.append("# Sarathi — evaluation test cases\n")
    out.append(
        "Every check in `src/ioe/eval.py`, listed. Generated by `notes/list_tests.py` "
        "straight from the suite, so it cannot drift from what actually runs.\n"
    )
    out.append(
        f"**{total} checks** — {len(cases)} single-turn cases, {conv_turns} conversation "
        f"turns across {len(suite.CONVERSATIONS)} threads, {figures} figure checks, plus "
        f"a detector precision check over {len(suite.MUST_FIRE)} task requests.\n"
    )
    out.append(
        "The suite asserts **which evidence the application assembled** before the model "
        "wrote anything — not the prose it wrote. `evaluation.md` explains why. Two "
        "columns therefore matter equally:\n"
    )
    out.append(
        "- **Must assemble** — the evidence that has to be in front of the model.\n"
        "- **Must not** — evidence that must be absent. This is where the subtle "
        "regressions show up: a fee question that *also* refuses is broken even though "
        "the figures arrived.\n"
    )
    out.append("Evidence names:\n")
    out.append("| Name | Means |")
    out.append("| --- | --- |")
    for name, meaning in MEANS.items():
        out.append(f"| `{name}` | {meaning} |")
    out.append("")
    out.append("---\n")

    # ---- single-turn cases, grouped ------------------------------------------
    seen: list[str] = []
    for group, *_ in cases:
        if group not in seen:
            seen.append(group)

    number = 0
    for group in seen:
        title, blurb = GROUPS.get(group, (group.title(), ""))
        rows = [case for case in cases if case[0] == group]
        out.append(f"## {title} — {len(rows)} cases\n")
        if blurb:
            out.append(f"{blurb}\n")
        out.append("| # | Question | Must assemble | Must not |")
        out.append("| ---: | --- | --- | --- |")
        for _, question, want, forbid in rows:
            number += 1
            out.append(f"| {number} | {question} | {names(want)} | {names(forbid)} |")
        out.append("")

    out.append("---\n")

    # ---- conversations --------------------------------------------------------
    out.append(f"## Conversations — {conv_turns} turns\n")
    out.append(
        "Single-turn cases cannot test continuity, and continuity is where the reported "
        "defects lived. Each thread runs turn by turn against one checkpointed "
        "conversation; every follow-up below is answerable and meaningless read alone.\n"
    )
    for group, turns in suite.CONVERSATIONS:
        out.append(f"### Thread `{group}` — {len(turns)} turns\n")
        out.append("| # | Turn | Must assemble | Must not |")
        out.append("| ---: | --- | --- | --- |")
        for index, (message, want, forbid) in enumerate(turns, 1):
            out.append(f"| {index} | {message} | {names(want)} | {names(forbid)} |")
        out.append("")

    out.append("---\n")

    # ---- figures --------------------------------------------------------------
    out.append(f"## Figure checks — {figures} checks\n")
    out.append(
        "The only cases that run generation. They exist because the design above has one "
        "blind spot: a block can be correct, the evidence assertion can pass, and the "
        "model can still read the wrong line out of it. Asked what the whole degree costs "
        "at Full Fee, the assistant once answered `218,070` — the admission-day total, "
        "printed on the line directly above the right one — and the suite reported "
        "success. These assert that one specific printed figure appears in the answer.\n"
    )
    for group, turns in suite.FIGURES:
        out.append(f"### Thread `{group}`\n")
        out.append("| # | Turn | Answer must state |")
        out.append("| ---: | --- | --- |")
        for index, (message, figure) in enumerate(turns, 1):
            out.append(f"| {index} | {message} | `{figure}` |")
        out.append("")

    out.append("---\n")

    # ---- detector -------------------------------------------------------------
    out.append(f"## Detector precision — {len(suite.MUST_FIRE)} task requests\n")
    out.append(
        "`scope.is_task_substitution` is the one deterministic thing between a student "
        'and "here\'s a simple Python function". Its danger is not missing one — it is '
        "firing on a genuine question, which is how an earlier scope guard broke "
        "conversations. So it is checked in both directions: it must catch all of these, "
        "**and stay silent on every other question in this document.**\n"
    )
    for index, message in enumerate(suite.MUST_FIRE, 1):
        out.append(f"{index}. {message}")
    out.append("")

    out.append("---\n")
    out.append("## Running them\n")
    out.append("```bash")
    out.append("uv run python -m ioe.eval                 # everything")
    out.append("uv run python -m ioe.eval fees            # one group")
    out.append("uv run python -m ioe.eval cutoffs chances # several")
    out.append(
        "uv run python -m ioe.eval figures         # only the answer-text checks"
    )
    out.append("```\n")
    out.append(
        "Exit status is the number of failures, so it is usable as a gate. The four data "
        "modules verify themselves separately — `uv run python -m ioe.fees`, `.seats`, "
        "`.cutoffs`, `.priority` — each re-deriving every published total from its line "
        "items and reporting any that disagree.\n"
    )

    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"{total} checks -> {OUT}")


if __name__ == "__main__":
    main()
